# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TenAgentCli < Formula
  desc "CLI tool for TEN-Agent"
  homepage "https://github.com/digitallysavvy/ten-agent-cli"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.6/ten-agent-cli_Darwin_x86_64.tar.gz"
      sha256 "94ad4fb34af001565f8c8ddf2dc048444af8b1cc8757e8b94629ae1d0de82e92"

      def install
        bin.install "ten-agent-cli"
      end
    end
    on_arm do
      url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.6/ten-agent-cli_Darwin_arm64.tar.gz"
      sha256 "319ed0a63f29e59e9bdf6eb28323a42ce48d783e6bcf4546df13a7cce7561c27"

      def install
        bin.install "ten-agent-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.6/ten-agent-cli_Linux_x86_64.tar.gz"
        sha256 "ad550b5c59269e7d9d14248e35f2fd9facf5c02e70ecbfbfc0fba7c5cff4d868"

        def install
          bin.install "ten-agent-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.6/ten-agent-cli_Linux_arm64.tar.gz"
        sha256 "f89abe2a7c2f748c478dec774ff52023d5a2e2c563d4cf2ff5e8668c5c92903d"

        def install
          bin.install "ten-agent-cli"
        end
      end
    end
  end
end
