# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TenAgent < Formula
  desc "CLI tool for TEN-Agent"
  homepage "https://github.com/digitallysavvy/ten-agent-cli"
  version "0.0.21"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.21/ten-agent_Darwin_x86_64.tar.gz"
      sha256 "56784dac38a8cbace96ecf5bdc49a0ebe327373140a0f20fe4f74fa635be11d5"

      def install
        bin.install "ten-agent"
      end
    end
    on_arm do
      url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.21/ten-agent_Darwin_arm64.tar.gz"
      sha256 "f2cad2e22f314fcf72957e02d79ed9423f30557d1620a4c9b90623faf11dd619"

      def install
        bin.install "ten-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.21/ten-agent_Linux_x86_64.tar.gz"
        sha256 "77c7a44aed2e1cdc2c9e4fbf10c84d38ae78b247503c674e6ac34fdc22e489ab"

        def install
          bin.install "ten-agent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.21/ten-agent_Linux_arm64.tar.gz"
        sha256 "c51f61c8915d1ea55071e92200a575317009b8ef8db9e912e2b9728186ce0c0a"

        def install
          bin.install "ten-agent"
        end
      end
    end
  end
end
