# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TenAgent < Formula
  desc "CLI tool for TEN-Agent"
  homepage "https://github.com/digitallysavvy/ten-agent-cli"
  version "0.0.31"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.31/ten-agent_Darwin_x86_64.tar.gz"
      sha256 "a5335bc5365aa53cf5b5f467d6b278b4d933b6f357f0bf1ad6d92638b1baa6e7"

      def install
        bin.install "ten-agent"
      end
    end
    on_arm do
      url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.31/ten-agent_Darwin_arm64.tar.gz"
      sha256 "76ba618451e3a7ed410b969eb082ea8c4dbda6582dc8e75cee78691cae6bfcae"

      def install
        bin.install "ten-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.31/ten-agent_Linux_x86_64.tar.gz"
        sha256 "18eacd4b4e871dc8aa82add76549403a61f7fe4260d307b69a960a7b0649274c"

        def install
          bin.install "ten-agent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitallysavvy/ten-agent-cli/releases/download/v0.0.31/ten-agent_Linux_arm64.tar.gz"
        sha256 "c55ecd727aa9b7c0241b746e1faf35de3c349a90e5d7ea9a3fa485dc514dcc5b"

        def install
          bin.install "ten-agent"
        end
      end
    end
  end
end
